# GoReleaser configuration for claude-yolo
# https://goreleaser.com/customization/

version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: claude-yolo
    main: ./cmd/claude-yolo
    binary: claude-yolo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: claude-yolo-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - examples/**/*
      - strategies/**/*
      - scripts/**/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Security'
      regexp: "^.*sec(urity)?[(\\w)]*:+.*$"
      order: 2
    - title: 'Documentation'
      regexp: "^.*docs?[(\\w)]*:+.*$"
      order: 3
    - title: 'Chores'
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 4
    - title: Others
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: rickgorman
    name: claude-yolo
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Installation

    ### macOS (Homebrew)
    ```bash
    # Coming soon
    brew install rickgorman/tap/claude-yolo
    ```

    ### Download Binary
    Download the appropriate binary for your platform from the assets below.

    ### Build from Source
    ```bash
    git clone https://github.com/rickgorman/claude-yolo.git
    cd claude-yolo
    git checkout {{ .Tag }}
    make build
    ```

  footer: |
    ## Docker Images

    The Docker strategy images are available in the `strategies/` directory.
    Build them locally or pull from the release assets.

    ## Verifying Releases

    Verify the checksums:
    ```bash
    sha256sum -c checksums.txt
    ```

    ## Full Changelog

    See [CHANGELOG.md](https://github.com/rickgorman/claude-yolo/blob/main/CHANGELOG.md) for detailed changes.

    ---

    **Full Changelog**: https://github.com/rickgorman/claude-yolo/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: claude-yolo
    repository:
      owner: rickgorman
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/rickgorman/claude-yolo
    description: "AI pair programming in isolated Docker containers"
    license: MIT
    folder: Formula
    test: |
      system "#{bin}/claude-yolo", "--help"
    install: |
      bin.install "claude-yolo"
      bash_completion.install "completions/claude-yolo.bash" => "claude-yolo"
      zsh_completion.install "completions/_claude-yolo" => "_claude-yolo"

announce:
  skip: true  # Manual announcements preferred
